# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Title of your website
title: 'Delta3Consulting'

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: 'Design, Develop, Deliver'

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: 'Design. Develop. Deliver'

# The credits show up in the includes/_footer.html – It would be nice of you to leave a link to Phlow or Feeling Responsive as a thank you :)
credits: ''

# Main author of the website
# See > authors.yml
author: Dustinson

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'https://delta3consulting.com'
baseurl: ''

# GitHub repository information (required for GitHub Pages)
repository: "dustinson/d3cblog.github.io"

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: https://dustinson.github.io/d3cblog.github.io/edit/gh-pages

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: 'https://delta3consulting.com/images/'


# Logo size is 600x80 pixels
logo: "D3Logo.png"

# Plugins
plugins:
    - jekyll-asciidoc
    - jekyll-gist
