#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml

# Force localhost for development
url: ''
baseurl: ''
urlimg: '/images/'

# Force all URLs to be relative
relative_permalinks: false

# Disable analytics in development
google_analytics_tracking_id: false

# Disable production optimizations
compress_html:
  enabled: false
