name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Only run on the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Update bundle platforms
        run: |
          gem install bundler
          bundle lock --add-platform x86_64-linux
          bundle install

      - name: Build site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Downgrade to v3 which is stable
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
