# Custom workflow for building and deploying a Jekyll site
# Updated on July 23, 2025 with alternative deployment method
name: Build and Deploy Jekyll Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Build job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build with Jekyll
        run: |
          bundle install
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      # Direct deployment using a well-tested action
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
          clean: true
