# Simple direct-deployment workflow for Jekyll
name: Jekyll Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Grant workflow full repo access for direct pushes
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # We need all history for proper date handling

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build with Jekyll
        run: |
          bundle install
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Setup Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Deploy to branch instead of using the API
      - name: Deploy directly to branch
        run: |
          # Save CNAME if it exists
          [ -f CNAME ] && cp CNAME _site/
          
          # Navigate to the build folder
          cd _site
          
          # Initialize git and push to main branch
          git init
          git add -A
          git commit -m "Deploy site built from commit ${{ github.sha }}"
          
          # Force push to the main branch (warning: this will overwrite the branch)
          git push -f https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git HEAD:main
